<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXx8n9uS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXx8n9uS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXx8n9uS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXx8n9uS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXx8n9uS\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xx8n9uS',
    'container.build_id' => 'ca9e5e5f',
    'container.build_time' => 1586450984,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXx8n9uS');
